### ISSUE TITLE
Support legacy-style projects

### ISSUE THREAD

**Issue by Sebbs128** [SimonCropp/Polyfill#101]
#### Is the feature request related to a problem

When the package is installed in an legacy-style project (that is, the project file format used prior to the current SDK-style; such as ASP.NET MVC5 projects), building that project fails because the `ResolvePackageAssets` target does not exist for MSBuild. 

[ETA]ASP.NET projects unfortunately can't be migrated to SDK-style at this time.

`ResolvePackageAssets` is a `Target` used within `Polyfill.targets`, but only exists in the dotnet SDK.

#### Describe the solution

I can currently work around this by adding a placeholder for `ResolvePackageAssets` if the target isn't already defined, and setting up some of the preprocessor constants that SDK-style projects set but are lacking in legacy style projects. In my work-around they're placed in `Directory.Build.props` and `Directory.Build.targets`, however for a solution in the Polyfill package itself these should be able to go in `Polyfill.props` and `Polyfill.targets`.

In legacy style projects, add `NETFRAMEWORK`; to `<DefineConstants>` (or add `<DefineConstants>NETFRAMEWORK</DefineConstants>` if the element didn't already exist).
 
Add to `Directory.Build.props` (work-around; `Polyfill.props` for potential PR)
```xml
    <PropertyGroup Condition="'$(TargetFramework)' == '' and '$(TargetFrameworkVersion)' == 'v4.8'">
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    <!-- repeat above for net47, and net46 -->
```

Add to `Directory.Build.targets` (work-around; `Polyfill.targets` for potential PR)
```xml
	<PropertyGroup>
		<ResolvePackageAssetsTargets Condition="Exists($(ResolvePackageAssets))">true</ResolvePackageAssetsTargets>
	</PropertyGroup>

	<Target Name="ResolvePackageAssets"
			Condition="'$(ResolvePackageAssetsTargets)' != 'true'"
			AfterTargets="ResolveReferences">
		<Message Importance="normal" Text="ResolvePackageAssets target doesn't exist. Adding a placeholder." />
	</Target>
```

#### Describe alternatives considered

The `buildMultitargeting` asset type was introduced in NuGet 4.0 to allow framework-specific build logic, however I don't think it's capable of distinguishing SDK-style from old-style projects.

I also looked at getting `ResolvePackageAssets` referenceable for building a legacy-style project, but getting a reference to the `.targets` file is a bit of a maze (and I wasn't yet able to find an MSBuild property that might allow referring to a dotnet SDK directory).

#### Additional context

[ETA] Context for not being able to switch ASP.NET projects to SDK-style (yet?)
https://github.com/dotnet/project-system/issues/2670

**Comment by SimonCropp** [comment]
what’s stopping you from moving to the new project format?

**Comment by Sebbs128** [comment]
That was one of the first things I tried. It's unsupported for ASPNET projects, and currently won't build (or little else). There is CZEMacLeod's alternative SDK for the project to target, but there's still several caveats to it.

**Comment by Sebbs128** [comment]
I've determined a better workaround after the previous one seemed to stop working, and even better it no longer needs replicating the contents of `Polyfill.props` and `Polyfill.targets`. (I'll update the original issue with these).

It does require that `NETFRAMEWORK` is added to `<DefineConstants>` in the legacy style projects, otherwise compiler errors in `/contentFiles/.../PolyfillExtensions_Type.cs` appear during a build (and for whatever reason, trying to add it in the `<PropertyGroup>` in `Directory.Build.props` wouldn't work).

In `Directory.Build.props`, I now just have

```xml
	<PropertyGroup Condition="'$(TargetFramework)' == '' and '$(TargetFramework)' == 'v4.8'">
		<TargetFramework>net48</TargetFramework>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' or '$(TargetFramework)' == 'net48'">
		<PackageReference Include="Polyfill" Version="1.30.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
```

And in `Directory.Build.targets`

```xml
	<PropertyGroup>
		<ResolvePackageAssetsTargets Condition="Exists($(ResolvePackageAssets))">true</ResolvePackageAssetsTargets>
	</PropertyGroup>

	<Target Name="ResolvePackageAssets"
			Condition="'$(ResolvePackageAssetsTargets)' != 'true'"
			AfterTargets="ResolveReferences">
		<Message Importance="normal" Text="ResolvePackageAssets target doesn't exist. Adding a placeholder." />
	</Target>
```

I'll see if I can get permission to contribute a PR during my work hours, otherwise I'll try and submit one after hours.

**Comment by maximpashuk** [comment]
My 50 cents

I also has a non-sdk style projects in my solution.
This is regular thing in legacy projects so my personal opinion that Polyfill should support them.

And it actually support it as for now with some workaround.
This is part of Directory.Build.props file I use as workaround

@Sebbs128 @SimonCropp I think proper fix sould use msbuild property UsingMicrosoftNETSdk to detect non-sdk style projects and not try to introducce fake TargetFramework property, it is not relevant in non-sdk style projects.

```xml
  <Target Name="ResolvePackageAssets" Condition=" '$(UsingMicrosoftNETSdk)' == '' " AfterTargets="ResolveReferences">
    <PropertyGroup>
      <DefineConstants>$(DefineConstants);NETFRAMEWORK</DefineConstants>
    </PropertyGroup>
  </Target>
```

**Comment by SimonCropp** [comment]
sorry. i dont think i have capacity to maintain support for legacy projects
