### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by skarllot** [SimonCropp/Polyfill#118]
### Is the feature request related to a problem
Provide a changelog to alow user keep up with changes made on each version.

### Describe the solution
The changelog can be provided or on a changelog file or using the Github releases page.

### Describe alternatives considered
None.

### Additional context
The [Polly](https://github.com/App-vNext/Polly) project is an example that provide both:
- [Changelog file](https://github.com/App-vNext/Polly/blob/ec47cfde8dfbc4d63d4e417a8daf4f61466da700/CHANGELOG.md)
- [Releases page](https://github.com/App-vNext/Polly/releases)

**Comment by SimonCropp** [comment]
i use closed milestones to track changes https://github.com/SimonCropp/Polyfill/milestones?state=closed

**Comment by skarllot** [comment]
Do you think that is enough? The Github releases page can generate the description automatically if releases are properly tagged and pull requests are used.

**Comment by SimonCropp** [comment]
i have tried several techniques to generating GH releases. none of them are OOTB. they all require more effort than using milestones, require manual setup, and are fragile to environment changes. i was using one on all my projects (100+) and it broke when a new version of .net was install on the gh agents. to move to another approach was a significant amount of research and manual work. 

so currently i have no plans to move off milestones

**Comment by skarllot** [comment]
What you think of making clear on the README file that "changelog" is on milestones and providing a link? Would help new comers.

**Comment by SimonCropp** [comment]
there already is one ![IMG_4972](https://github.com/SimonCropp/Polyfill/assets/122666/3390ed99-0fd4-418f-a665-79600dc59e4f)
