### ISSUE TITLE
Add polyfill for Enumerable.ToHashSet method

### ISSUE THREAD

**Issue by maximpashuk** [SimonCropp/Polyfill#121]
Enumerable.ToHashSet implemented for netstandard2.1 and net4x, **but not for netstandard2.0**.

https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.tohashset

As for me this slightly strange since netstandard2.0 is common subset between netstandard2.1 and net4x.

In my solution I have .net6.0 and legacy net472 projects and common logic between them in netstandard2.0.
I just want to have modern C# features in all projects and polyfill helps me in that, thanks a lot btw.

But my netstandard2.0 suffers from absense of ToHashSet method, I made it by myself very simple like

```
namespace System.Linq;

internal static class HashSetExtensions
{
    public static HashSet<TSource> ToHashSet<TSource>(this IEnumerable<TSource> source) =>
        source.ToHashSet(null);
    
    public static HashSet<TSource> ToHashSet<TSource>(
        this IEnumerable<TSource> source,
        IEqualityComparer<TSource> comparer)
    {
        if (source == null)
            throw new ArgumentNullException(nameof(source));
        return new HashSet<TSource>(source, comparer);
    }
}
```

Not sure is this code snippet helpful for you.

This will be to have support for ToHashSet method in netstandard2.0 projects

**Comment by SimonCropp** [comment]
happy to consider a pull request for this

**Comment by SimonCropp** [comment]
@maximpashuk https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by maximpashuk** [comment]
@SimonCropp I just tested the 2.1.0 version and it works as expected.
Thanks the quick fix.
