### ISSUE TITLE
Does this project support let .net 7 and .net 8 running on Old-OS such as windows7, windows8, and Windows10 ver<1809? ?

### ISSUE THREAD

**Issue by sgf** [SimonCropp/Polyfill#126]
Does this project support let .net 7 and .net 8 running on Old-OS such as windows7, windows8, and Windows10 ver<1809 ?
due to:https://github.com/dotnet/core/issues/7556

**Comment by SimonCropp** [comment]
no it doesnt. it helps you use net 8 features in earlier versions of .net
