### ISSUE TITLE
Missing milestone for 2.6.4 and 2.6.5

### ISSUE THREAD

**Issue by skarllot** [SimonCropp/Polyfill#140]
#### Preamble
Missing milestone for 2.6.4 and 2.6.5.

#### Describe the bug
The versions 2.6.4 and 2.6.5 was released but milestones was not created for them.

#### Minimal Repro
N/A

#### Submit a PR that fixes the bug
N/A

**Comment by SimonCropp** [comment]
i had two failed nuget released. so i have unlisted the bad ones. and here is the latest milestone 
https://github.com/SimonCropp/Polyfill/milestone/54
