### ISSUE TITLE
What about HashSet<T>.TryGetValue

### ISSUE THREAD

**Issue by maximpashuk** [SimonCropp/Polyfill#142]
I am not sure is it technacally possible to add polyfill for HashSet<T>.TryGetValue method for netstandard2.0 projects.

documentation
https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1.trygetvalue

This method was implemented separately in net472 and netstandard2.1 but not in netstandard2.0, this is surpise for me.
I afraid that implementation of this method required access to internal state of HashSet, I am just want to ask do you have an idea how this functionality can be polyfilled ?

**Comment by SimonCropp** [comment]
yep that should be possible. happy to accept a pull request that adds HashSet.TryGetValue

**Comment by maximpashuk** [comment]
Wow thats great, I will test it, many thanks!
