### ISSUE TITLE
ConcurrentDictionary.GetOrAdd<TArg>(TKey, Func<TKey,TArg,TValue>, TArg)

### ISSUE THREAD

**Issue by hazzik** [SimonCropp/Polyfill#158]
Please consider adding [`ConcurrentDictionary.GetOrAdd<TArg>(TKey, Func<TKey,TArg,TValue>, TArg)`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.getoradd?view=net-8.0#system-collections-concurrent-concurrentdictionary-2-getoradd-1(-0-system-func((-0-0-1))-0)) method. 

This method exists to allow adding values without allocation of closures.

**Comment by SimonCropp** [comment]
that should be doable. will look into tonight

**Comment by SimonCropp** [comment]
eta 30min

**Comment by hazzik** [comment]
Thanks
