### ISSUE TITLE
PackageDependencies contain unusable transitive dependencies

### ISSUE THREAD

**Issue by hazzik** [SimonCropp/Polyfill#164]
#### Describe the bug

I wanted to try using Polyfill in NHibernate, but it refuses to compile. It thinks that `FeatureMemory` is set. However, I do not have explicitly referenced `System.Memory`.

So I'm getting a lot of errors like this from the Polyfill when building .NET Standard 2.0 or .NET Core App 2.0:

> 0>DefaultInterpolatedStringHandler.cs(146,14): Error CS0246 : The type or namespace name 'ReadOnlySpan<>' could not be found (are you missing a using directive or an assembly reference?)

The reason it thinks `FeatureMemory` is set is because `PackageDependencies` in `PreparePolyfill` contain transitive dependencies. These transitive dependencies are not usable in the code, therefore I'm getting the error.

The .NET Standard 2.0 and .NET Core App 2.0 targets depend on [`System.Configuration.ConfigurationManager` 4.7.0](https://www.nuget.org/packages/System.Configuration.ConfigurationManager/4.7.0#dependencies-body-tab) that depends on [`System.Security.Cryptography.ProtectedData` 4.7.0](https://www.nuget.org/packages/System.Security.Cryptography.ProtectedData/4.7.0#dependencies-body-tab) that depends on `System.Memory` 4.5.3

#### Minimal Repro

```bash
dotnet new classlib -f "netstandard2.0" --langVersion latest
dotnet add package Polyfill
dotnet build # Build succeeded. / 0 Warning(s) / 0 Error(s)
dotnet add package System.Configuration.ConfigurationManager -v 4.7.0
dotnet build # Build FAILED. / 0 Warning(s) / 94 Error(s)
```

**Comment by hazzik** [comment]
Or, maybe the problem is in System.Configuration.ConfigurationManager v4.7.0 package. Because 6.0.0 and above do work for .NET Standard 2.0 target, and `System.Memory` seem to be visible to the code. 

Problem is that I cannot use versions above 4.7.0 for .NET Core App 2.0 targets: 5.0.0 is marked as not supported and 6.0.0 complains that .NET Core App 2.0 is not supported and I have to upgrade to .NET Core App 3.1.

**Comment by SimonCropp** [comment]
perhaps because the  System.Security.Cryptography.ProtectedData 4.7.0 nuepec has

```
      <group targetFramework=".NETStandard2.0">
        <dependency id="System.Memory" version="4.5.3" exclude="Compile" />
      </group>
```

??

I have no idea how to detect that.

can u add an explicit ref to System.Memory to work around it?

**Comment by hazzik** [comment]
Yeah, maybe this is the reason. 

> can u add an explicit ref to System.Memory to work around it?

I'll try to convince rest of the team.

**Comment by SimonCropp** [comment]
happy to release a fix. but i could not work out how to detect it in msbuild. 

any ideas

**Comment by hazzik** [comment]
After some digging in here: https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs and here: https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.PackageDependencyResolution.targets

I wanted to use `ResolvedCompileFileDefinitions`, but unfortunately it, for some reason, does not contain `System.ValueTuple`. :-/

**Comment by hazzik** [comment]
Ok, that is because on .NET Standard 2.0 it is not needed.
