### ISSUE TITLE
Int128, UInt128

### ISSUE THREAD

**Issue by RReverser** [SimonCropp/Polyfill#184]
#### Is the feature request related to a problem

.NET 7+ has added support for 128-bit integers - [Int128](https://learn.microsoft.com/en-us/dotnet/api/system.int128) and [UInt128](https://learn.microsoft.com/en-us/dotnet/api/system.uint128) correspondingly - but those don't exist in .NET standard, making it difficult to create libraries that depend on those larger integers but need to target platforms without .NET 7 (like Unity).

#### Describe the solution

Polyfill those APIs in the `Polyfill` package.

#### Describe alternatives considered

Polyfill those APIs in a new, separate NuGet package.

#### Additional context

Those are .NET only features with no changes to C# itself (notably, no new keyword, unlike for other integer types), so they should be relatively straightforward to implement in compatible fashion outside the .NET itself.

**Comment by SimonCropp** [comment]
wouldnt this suffuce? https://github.com/LEI-Hongfaan/UltimateOrb.Core

**Comment by RReverser** [comment]
I've seen those, but they predate System APIs and are not strictly polyfills.

I'm looking for something that can specifically polyfill standard .NET APIs for older .NET versions, just like we can do for new attributes and other stuff.

**Comment by SimonCropp** [comment]
given no libraries/apis you would be targeting would support those types, how useful is this?

**Comment by RReverser** [comment]
> given no libraries/apis you would be targeting would support those types

But that's the thing, as a library developer, I _could_ use it if polyfill existed. Right now I have to build some libraries separately for .NET 8 and .NET Standard 2.1 just because of a single `#if` to provide extra support for `Int128` types.

With this approach, I could instead build a single assembly that always references `System.Int128` and point users to the `Polyfill` package for targets where that type doesn't exist.

It's not very different from every other new .NET API polyfilled in this package in terms of usecases.

**Comment by SimonCropp** [comment]
> With this approach, I could instead build a single assembly that always references System.Int128 and point users to the Polyfill package for targets where that type doesn't exist.

that would break as soon as you have two libraires referencing Polyfill, since the types would conflict.

also the value of this would be limited by the fact that none of the core libraries would support these types. eg none of the `Math` apis would work. also none of the serialization libraries would recognize it.

this is simply not a workable solution moving forward. it would cause too many issues for consumers and be complex to explain the caveats.

so closing this for now
