### ISSUE TITLE
ArrayPool doesn't exist, needs System.Buffers

### ISSUE THREAD

**Issue by Bouke** [SimonCropp/Polyfill#193]
#### Describe the bug

When I have a reference to the latest version of `Microsoft.AspNetCore.DataProtection.EntityFrameworkCore` available to `net48`, compilation with Polyfill fails with these errors:

> DefaultInterpolatedStringHandler.cs(75,41): Error CS0103 : The name 'ArrayPool' does not exist in the current context  
DefaultInterpolatedStringHandler.cs(88,41): Error CS0103 : The name 'ArrayPool' does not exist in the current context  
DefaultInterpolatedStringHandler.cs(142,13): Error CS0103 : The name 'ArrayPool' does not exist in the current context  
DefaultInterpolatedStringHandler.cs(673,24): Error CS0103 : The name 'ArrayPool' does not exist in the current context  
DefaultInterpolatedStringHandler.cs(681,13): Error CS0103 : The name 'ArrayPool' does not exist in the current context  
Polyfill_TextWriter.cs(82,20): Error CS0103 : The name 'ArrayPool' does not exist in the current context  
Polyfill_TextWriter.cs(105,20): Error CS0103 : The name 'ArrayPool' does not exist in the current context  
------- Finished building project: Library. Succeeded: False. Errors: 7. Warnings: 0  

After adding a dependency on `System.Buffers`, the build succeeds.

#### Minimal Repro

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>12</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="2.2.8" />
    <PackageReference Include="Polyfill" Version="5.6.0" />
  </ItemGroup>
</Project>
```

#### Discussion

Should `System.Buffers` be a required dependency?

**Comment by SimonCropp** [comment]
this should now be fixed
