### ISSUE TITLE
ReadOnlySpan<char>.Split support

### ISSUE THREAD

**Issue by lahma** [SimonCropp/Polyfill#214]
#### Is the feature request related to a problem

This feature request would allow some performance optimizations for NET 6+ targets before NET 9.

#### Describe the solution

[SpanSplitEnumerator](https://github.com/dotnet/runtime/pull/104534) was merged and the PR basically contains the needed code. Of course would need preprocessor directives to check for NET 6 or greater and less than NET 9 (to get `SearchValues` and friends easily).  

#### Describe alternatives considered

One can always split with allocations 💣 

#### Additional context

I'm unsure if I have the capacity to create the PR, even though I fully understand it would be desirable from maintainer's point of view. The coding conventions and rules, I'm not yet familiar with.

**Comment by SimonCropp** [comment]
6.6.0 should hit nuget in approx 20min

**Comment by lahma** [comment]
Thank you, great addition!

**Comment by SimonCropp** [comment]
i found one more mem tweak https://github.com/SimonCropp/Polyfill/pull/217. so u prob want 6.6.1
