### ISSUE TITLE
Build error with `SplitAny(ReadOnlySpan<T>, params ReadOnlySpan<T>)`

### ISSUE THREAD

**Issue by samtrion** [SimonCropp/Polyfill#218]
If `LangVersion` `preview` is not activated, build errors occur.
![image](https://github.com/user-attachments/assets/27311210-ffce-4165-9718-f23b5ef47bb5)

**Comment by SimonCropp** [comment]
can u try v 6.6.2

**Comment by samtrion** [comment]
Works fine
