### ISSUE TITLE
PolyPublic doesn't work on simple library projects

### ISSUE THREAD

**Issue by brantburnett** [SimonCropp/Polyfill#38]
#### Preamble

This applies to simple library projects, such as a netstandard2.0 library. In this case, some complex workarounds are required to make the PolyPublic property make the members public.

This probably isn't a common practice, since if you're creating a library you probably want to keep the members internal. However, we're dealing with a large and complex multi-project application built on over 100 libraries. So we're building a single project that includes these polyfills along with some other common helpers. The idea is that having all the polyfills in a single assembly will keep our distribution code size and JIT memory footprint low rather than having 100 copies of the polyfills.

#### Describe the bug

A simple project like this results in an output assembly that does not have public members.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <PolyPublic>true</PolyPublic>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Polyfill" Version="1.18.0">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
  </ItemGroup>
</Project>
```

This appears to be because the NuGet `Build.props` file is imported at the "top" of the project by the build system, before any local properties are set.

#### Minimal Repro

See above csproj example.

#### Workaround

Changing the load order to set properties before the SDK works, but is cumbersome. This is done by removing the `Sdk` from the main `Project` element and instead manually importing the `Sdk.props` and `Sdk.targets` at the correct locations in the project file.

```xml
<Project>
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <PolyPublic>true</PolyPublic>
  </PropertyGroup>

  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk"  />

  <ItemGroup>
    <PackageReference Include="Polyfill">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
  </ItemGroup>

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk"  />
</Project>
```

#### Possible fixes

It may be possible to fix this by moving some values from `props` to `targets` in the NuGet package. However, I'm unsure what other side effects this may have. For example, it makes overriding values set in `props` more problematic.

Another solution may be to update the documentation to include the workaround.

**Comment by SimonCropp** [comment]
can u try 1.20.0

**Comment by brantburnett** [comment]
@SimonCropp This works great now, thanks.
