### ISSUE TITLE
Constants set altough conditions are not met

### ISSUE THREAD

**Issue by Corniel** [SimonCropp/Polyfill#65]
During the code generation of Polyfill on my project, the `ValueTupleReferenced`, and `MemoryReferenced` constants where set, although the project did not included `System.ValueTuple` or `System.Memory`. 

My workaround was to include those references (as they can be useful anyway), but I guess it is a bug.

The [Qowaiv PR 316](https://github.com/Qowaiv/Qowaiv/pull/316) that might help you reproduce the issue.

**Comment by SimonCropp** [comment]
i had a look at your repro. removed ` <PackageReference Include="System.ValueTuple" Version="4.5.0" />` and it still build.

perhaps u can provide a minimal repro as a pull request

**Comment by Corniel** [comment]
See: https://github.com/Qowaiv/Qowaiv/actions/runs/5705652616/job/15460542725?pr=317

**Comment by SimonCropp** [comment]
can provide a minimal repro as a pull request

**Comment by Corniel** [comment]
> can provide a minimal repro as a pull request

You can? Or Can I? I do not understand your comment.

**Comment by SimonCropp** [comment]
as in: can you submit a pull request that demonstrates the problem
