### ISSUE TITLE
Add DateOnly and TimeOnly support

### ISSUE THREAD

**Issue by tompazourek** [SimonCropp/Polyfill#73]
Polyfills for the `System.DateOnly` and `System.TimeOnly` types would be nice as well.

This library has it [Portable.System.DateTimeOnly](https://github.com/OlegRa/System.DateTimeOnly).

What do you think? Good idea, bad idea?

**Comment by tompazourek** [comment]
I think it's still very useful in case you are designing (or consuming) Web APIs. The service that publishes the API might be from newer .NET version and uses these types, and sometimes you need to consume it in an older .NET version.

Also, it's often not difficult to add support for DateOnly/TimeOnly to serialize/deserialize in certain format, or older EF, etc. In Newtonsoft.Json, it's almost trivial.

To talk numbers, the [Portable.System.DateTimeOnly](https://www.nuget.org/packages/Portable.System.DateTimeOnly/) package has over 132K downloads. I think that illustrates that it has value to the users.

It's also possible to use that package together with Polyfill. However, I see great value in having an unified package that does it all. But I'm not sure if this is your vision for Polyfill. If you want to cover as much as possible, or only the selected most useful polyfills.

How about leaving this issue open for a while and see if it gains some interest from other users?

**Comment by SimonCropp** [comment]
closing this one since there doesnt seem to be more interest
